spring.datasource.url=jdbc:postgresql://localhost:5432/powerauth

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-module.xml

powerauth.service.scheduled.job.fido2AuthenticatorCacheEviction=60000

powerauth.server.db.master.encryption.algorithm=NO_ENCRYPTION

logging.level.com.wultra=DEBUG
logging.level.com.wultra.core.audit=INFO
