services:
  postgresql:
    image: postgres:17
    container_name: pa-postgresql
    environment:
      POSTGRES_PASSWORD: "YourStrong_Passw0rd"
    ports:
      - "5432:5432"
    volumes:
      - ~/dev/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
